Repository NEO-TAT/tat_flutter, pull requests merged in 2023-10, with the labels that each got.

#205 Fix: Reload error happened on zh-tw corse information page
  lib/src/connector/course_connector.dart
Labels: type: bug, priority: high, status: ready to merge

#206 Fix: Loading error since the ISchool change the redirect mechanism
  lib/src/connector/ischool_plus_connector.dart
Labels: type: bug, priority: high, status: ready to merge

#201 Update GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: scope: documentation, type: enhancement, priority: low

#208 Upgrade dependency versions for v1.4.5
  android/app/build.gradle
  android/build.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/beta.xcscheme
  ios/Runner.xcodeproj/xcshareddata/xcschemes/real.xcscheme
  pubspec.lock
  pubspec.yaml
Labels: priority: medium

#207 Release/1.4.5
  android/app/build.gradle
  android/build.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/beta.xcscheme
  ios/Runner.xcodeproj/xcshareddata/xcschemes/real.xcscheme
  pubspec.lock
  pubspec.yaml
Labels: priority: high
