Repository NEO-TAT/tat_flutter, pull requests merged in 2024-12, with the labels that each got.

#240 chore: apply diffs generated by Flutter 3.7.12 during build
  android/app/build.gradle
  android/build.gradle
Labels: priority: low, scope: android

#239 chore: add Flutter Version Manager configuration
  .fvmrc
  .gitignore
  .vscode/settings.json
  README.md
Labels: priority: low

#212 Contributors page render error
  lib/ui/pages/other/page/contributors_page.dart
Labels: priority: low, scope: ui/ux
