Repository NEO-TAT/tat_flutter, pull requests merged in 2024-02, with the labels that each got.

#218 Optimize the category loading in score page
  lib/src/connector/course_connector.dart
  lib/src/model/course/course_syllabus_json.dart
  lib/src/model/json_init.dart
  lib/src/task/course/course_category_task.dart
  lib/ui/pages/score/score_page.dart
Labels: type: enhancement, priority: medium

#228 Return type error when student list fetch exception happened
  lib/src/connector/ischool_plus_connector.dart
Labels: type: bug, priority: critical

#225 Update ischool login method with retry mechanism
  .gitignore
  lib/src/connector/ischool_plus_connector.dart
  lib/src/task/iplus/iplus_system_task.dart
  test/ischool_plus_connector_test/ischool_plus_connector_test.dart
Labels: type: enhancement, priority: medium

#229 修復「誤用 null courseMainInfo」的問題
  lib/ui/pages/coursedetail/screen/course_info_page.dart
Labels: type: bug, priority: medium

#230 Release/1.6.0
  pubspec.yaml
Labels: type: enhancement, priority: medium
